version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports: 
      - '27017:27017'
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  ml-client:
    build: ./machine-learning-client
    ports:
      - '1000:1000'
    depends_on:
      - mongo
    networks:
      - app-network

  webapp:
    build: ./web-app
    ports:
      - '5000:5000'
    depends_on:
      - mongo
      - ml-client
    networks:
      - app-network
    environment:
      - "FRAME_SRC=http://ml-client:1000"

networks:
  app-network:
    driver: bridge