version: "3.8"

services:
  db:
    image: mongo:latest
    privileged: true
    ports: 
      - '27017:27017'
    volumes:
      - db_data:/data/db

  webapp:
    build: ./web-app
    privileged: true
    ports:
      - '5000:5000'
    depends_on:
      - db

  ml-client:
    build: ./machine-learning-client
    privileged: true
    ports:
      - '1000:1000'
    depends_on:
      - db
  
volumes:
  db_data: